### login
GET https://localhost:5000/login HTTP/1.1
Authorization: Basic admin:12345

###
POST https://localhost:5000/games HTTP/1.1
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkNzZmNTgwMC04YjEwLTRiNWItODA3NS00M2EwOTcxMGZhMWEiLCJleHAiOjE1OTAzNjM4NjN9.BQcF_Gs1NTvx4E8w4VfiMkpOkeeOQTAVXUrtQKXDj4E
Content-Type: application/json

{
    "name": "测试对局4444",
    "comment": "ka rer",
    "blackone_id": "sunlf1",
    "blacktwo_id": "sunlf2",
    "whiteone_id": "sunlf3",
    "whitetwo_id": "admin",
    "dur_date":"2020-10-22 22:23:00",
    "total_time": 200,
    "public": true,
    "password": null
}

###
GET  https://localhost:5000/games HTTP/1.1
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkNzZmNTgwMC04YjEwLTRiNWItODA3NS00M2EwOTcxMGZhMWEiLCJleHAiOjE1OTAzMDMxMDR9.qYRNRKQzZtFeZeNLAy19kiH6PgqjlC5QTkRRfaKuOVc

####

POST  https://localhost:5000/kifus HTTP/1.1
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkNzZmNTgwMC04YjEwLTRiNWItODA3NS00M2EwOTcxMGZhMWEiLCJleHAiOjE1OTAxNTU3MjF9.MQdiSC_EGk2frgJObK31IJgL4GM09vokQAw3eV0IBtg
Content-Type: application/json

{"black_info":"sunlf1&sunlf2","white_info":"sunlf3&admin","kifu_data":"(;TM[3400]KM[7.5]PB[sunlf1&sunlf2]PW[sunlf3&admin]SZ[19]AP[WGo.js:2]FF[4]GM[1]CA[UTF-8]BL[3400]WL[3400]B[pd]BL[3400]WL[3400])","result":"白中盘胜"}


###
GET  https://localhost:5000/kifus HTTP/1.1
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkNzZmNTgwMC04YjEwLTRiNWItODA3NS00M2EwOTcxMGZhMWEiLCJleHAiOjE1OTAzNjM4NjN9.BQcF_Gs1NTvx4E8w4VfiMkpOkeeOQTAVXUrtQKXDj4E