### 用户登陆
GET https://localhost:5000/login HTTP/1.1
Authorization: Basic admin:1

### 注册用户
POST https://localhost:5000/users
Content-Type: application/json

{
    "name": "kalix3",
    "password": "12345",
    "email":"sunlin@qq.com",
    "mobile":"11313"
}


 
### get all users

GET https://localhost:5000/users HTTP/1.1
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkNzZmNTgwMC04YjEwLTRiNWItODA3NS00M2EwOTcxMGZhMWEiLCJleHAiOjE1ODk5NTU3NDF9.U4d7U_AyY7bZENINuDd1JvfT5LpgZYUBG64xS4H0El8

### create a new user

POST https://localhost:5000/users HTTP/1.1
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiI0ZjAzYTA2OS02ZjhlLTQwMjYtYTg4NC05YTAzNGRmM2I1MTUiLCJleHAiOjE1ODk2MDMyMzh9.7E4A4uy8cvR3ibhRv0TIusEs0G0unQFUbd8wQe-7Jkc"
Content-Type: application/json

{
    "name": "sunlf3",
    "password": "123"
}

### 查看一个用户
GET https://localhost:5000/users/data?userName=admin

### create a new kifu

POST https://localhost:5000/kifus HTTP/1.1
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkNzZmNTgwMC04YjEwLTRiNWItODA3NS00M2EwOTcxMGZhMWEiLCJleHAiOjE1ODk3ODM5Njd9.W_4sZE6N7G30lL1WgQKZc8X_0AZIcU3Urj7XIvhAYNE
Content-Type: application/json

{
    "kifu_data": "sunlf1232434",
    "black_info": "kalix1212erer",
    "white_info": "kalixwewew1212erer"
}

### create a new kifu

GET https://localhost:5000/kifus/1 HTTP/1.1
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOiJkNzZmNTgwMC04YjEwLTRiNWItODA3NS00M2EwOTcxMGZhMWEiLCJleHAiOjE1ODk3ODM5Njd9.W_4sZE6N7G30lL1WgQKZc8X_0AZIcU3Urj7XIvhAYNE

